apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: myrs2-ready
spec:
   replicas: 3
   selector:
     matchLabels:
      env: dev
   template:
     metadata:
       labels:
         env: dev
     spec:
       containers:
        - image: nginx
          name: mycont
          ports:
            - containerPort: 80
          readinessProbe: 
            httpGet: 
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 2
            successThreshold: 1

