apiVersion: v1
kind: ReplicationController
metadata:
   name: myrc-pod
spec:
   replicas: 3
   selector:
      env: test
   template:
     metadata:
       labels:
         env: test
     spec:
       containers:
        - image: nginx
          name: mycont
          ports:
            - containerPort: 80
