apiVersion: v1
kind: ReplicationController
metadata:
   name: myrc1-pod
spec:
   replicas: 5
   selector:
      env: dev
   template:
     metadata:
       labels:
         env: dev
     spec:
       containers:
        - image: nginx
          name: mycont
          ports:
            - containerPort: 80
