apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: myrs-nodeport
spec:
   replicas: 3
   selector:
     matchLabels:
      app: facebook
   template:
     metadata:
       labels:
         app: facebook
     spec:
       containers:
        - image: nginx
          name: mycont
          ports:
            - containerPort: 80
